import {
  Student,
  Professor,
  Category,
  ConfirmationRequest,
  Season,
  Package,
  Product,
  Attendance,
  User,
} from './types';
import { subDays, subHours, addHours, format } from 'date-fns';
import { getImage } from './placeholder-images';

export const users: User[] = [
  { id: 'user-1', name: 'Admin', email: 'admin@example.com', avatarUrl: 'https://picsum.photos/seed/admin/100/100', role: 'Administrador' },
  { id: 'user-2', name: 'Sofia Rodriguez', email: 'promotora@example.com', avatarUrl: 'https://picsum.photos/seed/promo1/100/100', role: 'Promotora' },
  { id: 'user-3', name: 'Luisa Martinez', email: 'luisa@sportingclub.com', avatarUrl: 'https://picsum.photos/seed/promo2/100/100', role: 'Promotora' },
]

export const professors: Professor[] = [
  {
    id: 'prof-1',
    name: 'Alberto Domínguez',
    sport: 'Fútbol',
    phone: '987654321',
    email: 'alberto.d@example.com',
    categoryIds: ['cat-15', 'cat-17'],
  },
  {
    id: 'prof-2',
    name: 'Carlos Orellano',
    sport: 'Fútbol',
    phone: '912345678',
    email: 'carlos.o@example.com',
    categoryIds: ['cat-13', 'cat-12'],
  },
  {
    id: 'prof-3',
    name: 'Ricardo Mendez',
    sport: 'Fútbol',
    phone: '998877665',
    email: 'ricardo.m@example.com',
    categoryIds: ['cat-10', 'cat-8', 'cat-6'],
  },
];

export const categories: Category[] = [
  {
    id: 'cat-17',
    name: 'Sub 17',
    sport: 'Fútbol',
    ageRange: [16, 17],
    maxCapacity: 25,
    enrolledStudents: 20,
    professors: ['Alberto Domínguez'],
    schedule: {
      days: ['Lunes', 'Miércoles', 'Viernes'],
      time: '08:00 a 10:00',
      durationPerClass: '2 horas',
      frequency: '3 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-05',
  },
  {
    id: 'cat-15',
    name: 'Sub 15',
    sport: 'Fútbol',
    ageRange: [14, 15],
    maxCapacity: 30,
    enrolledStudents: 28,
    professors: ['Alberto Domínguez'],
    schedule: {
      days: ['Lunes', 'Miércoles', 'Viernes'],
      time: '10:00 a 12:00',
      durationPerClass: '2 horas',
      frequency: '3 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-05',
  },
  {
    id: 'cat-13',
    name: 'Sub 13',
    sport: 'Fútbol',
    ageRange: [13, 13],
    maxCapacity: 30,
    enrolledStudents: 30,
    professors: ['Carlos Orellano'],
    schedule: {
      days: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
      time: '14:00 a 15:30',
      durationPerClass: '1 hora y 30 minutos',
      frequency: '5 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-06',
  },
  {
    id: 'cat-12',
    name: 'Sub 12',
    sport: 'Fútbol',
    ageRange: [11, 12],
    maxCapacity: 25,
    enrolledStudents: 22,
    professors: ['Carlos Orellano'],
    schedule: {
      days: ['Martes', 'Jueves', 'Sábado'],
      time: '16:00 a 18:00',
      durationPerClass: '2 horas',
      frequency: '3 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-07',
  },
  {
    id: 'cat-10',
    name: 'Sub 10',
    sport: 'Fútbol',
    ageRange: [9, 10],
    maxCapacity: 20,
    enrolledStudents: 18,
    professors: ['Ricardo Mendez'],
    schedule: {
      days: ['Lunes', 'Miércoles', 'Viernes', 'Sábado'],
      time: '09:00 a 11:00',
      durationPerClass: '2 horas',
      frequency: '4 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-06',
  },
  {
    id: 'cat-8',
    name: 'Sub 8',
    sport: 'Fútbol',
    ageRange: [7, 8],
    maxCapacity: 20,
    enrolledStudents: 15,
    professors: ['Ricardo Mendez'],
    schedule: {
      days: ['Martes', 'Jueves', 'Sábado'],
      time: '09:00 a 10:30',
      durationPerClass: '1 hora y 30 minutos',
      frequency: '3 veces por semana',
    },
    price: 25.00,
    startDate: '2026-02-06',
  },
  {
    id: 'cat-6',
    name: 'Sub 6',
    sport: 'Fútbol',
    ageRange: [4, 6],
    maxCapacity: 15,
    enrolledStudents: 10,
    professors: ['Ricardo Mendez'],
    schedule: {
      days: ['Sábado'],
      time: '08:00 a 09:30',
      durationPerClass: '1 hora y 30 minutos',
      frequency: '1 vez por semana',
    },
    price: 20.00,
    startDate: '2026-02-07',
  },
];

export const students: Student[] = [
  {
    id: 'stu-1',
    name: 'Juan Perez Garcia',
    dni: '78945612',
    photoUrl: 'https://picsum.photos/seed/stu1/100/100',
    age: 15,
    gender: 'Masculino',
    guardian: { name: 'Mario Perez', dni: '45612378', phone: '987654321' },
    sport: 'Fútbol',
    category: 'Sub 15',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-1',
    totalPayments: 3,
    totalAttendance: 22,
  },
  {
    id: 'stu-2',
    name: 'Maria Lopez Torres',
    dni: '87654321',
    photoUrl: 'https://picsum.photos/seed/stu2/100/100',
    age: 13,
    gender: 'Femenino',
    guardian: { name: 'Ana Torres', dni: '12345678', phone: '912345678' },
    sport: 'Fútbol',
    category: 'Sub 13',
    season: 'Verano 2026',
    paymentStatus: 'Deuda pendiente',
    professorId: 'prof-2',
    totalPayments: 1,
    totalAttendance: 15,
  },
  {
    id: 'stu-3',
    name: 'Carlos Sanchez Ruiz',
    dni: '12345679',
    photoUrl: 'https://picsum.photos/seed/stu3/100/100',
    age: 18,
    gender: 'Masculino',
    phone: '998877665',
    sport: 'Fútbol',
    category: 'Sub 17',
    season: 'Anual 2026',
    paymentStatus: 'Próximo a vencer',
    professorId: 'prof-1',
    totalPayments: 5,
    totalAttendance: 45,
  },
  {
    id: 'stu-4',
    name: 'Ana Gomez Flores',
    dni: '98765432',
    photoUrl: 'https://picsum.photos/seed/stu4/100/100',
    age: 10,
    gender: 'Femenino',
    guardian: { name: 'Luis Gomez', dni: '23456789', phone: '987123456' },
    sport: 'Fútbol',
    category: 'Sub 10',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-3',
    totalPayments: 2,
    totalAttendance: 18,
  },
  {
    id: 'stu-5',
    name: 'Pedro Ramirez Soto',
    dni: '54321678',
    photoUrl: 'https://picsum.photos/seed/stu5/100/100',
    age: 12,
    gender: 'Masculino',
    guardian: { name: 'Laura Soto', dni: '67891234', phone: '976543210' },
    sport: 'Fútbol',
    category: 'Sub 12',
    season: 'Anual 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-2',
    totalPayments: 6,
    totalAttendance: 50,
  },
  // Additional students
  {
    id: 'stu-6',
    name: 'Diego Vargas Rios',
    dni: '65432198',
    photoUrl: 'https://picsum.photos/seed/stu6/100/100',
    age: 16,
    gender: 'Masculino',
    guardian: { name: 'Roberto Vargas', dni: '32198765', phone: '945678901' },
    sport: 'Fútbol',
    category: 'Sub 17',
    season: 'Anual 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-1',
    totalPayments: 4,
    totalAttendance: 30,
  },
  {
    id: 'stu-7',
    name: 'Valentina Cruz Mora',
    dni: '43219876',
    photoUrl: 'https://picsum.photos/seed/stu7/100/100',
    age: 8,
    gender: 'Femenino',
    guardian: { name: 'Patricia Cruz', dni: '98761234', phone: '956789012' },
    sport: 'Fútbol',
    category: 'Sub 8',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-3',
    totalPayments: 2,
    totalAttendance: 12,
  },
  {
    id: 'stu-8',
    name: 'Mateo Jimenez Palma',
    dni: '21987654',
    photoUrl: 'https://picsum.photos/seed/stu8/100/100',
    age: 5,
    gender: 'Masculino',
    guardian: { name: 'Sergio Jimenez', dni: '76543210', phone: '967890123' },
    sport: 'Fútbol',
    category: 'Sub 6',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-3',
    totalPayments: 1,
    totalAttendance: 8,
  },
  {
    id: 'stu-9',
    name: 'Lucia Fernandez Vega',
    dni: '19876543',
    photoUrl: 'https://picsum.photos/seed/stu9/100/100',
    age: 14,
    gender: 'Femenino',
    guardian: { name: 'Carmen Vega', dni: '87654390', phone: '978901234' },
    sport: 'Fútbol',
    category: 'Sub 15',
    season: 'Anual 2026',
    paymentStatus: 'Deuda pendiente',
    professorId: 'prof-1',
    totalPayments: 2,
    totalAttendance: 20,
  },
  {
    id: 'stu-10',
    name: 'Santiago Torres Lara',
    dni: '87654310',
    photoUrl: 'https://picsum.photos/seed/stu10/100/100',
    age: 11,
    gender: 'Masculino',
    guardian: { name: 'Jose Torres', dni: '54310876', phone: '989012345' },
    sport: 'Fútbol',
    category: 'Sub 12',
    season: 'Verano 2026',
    paymentStatus: 'Próximo a vencer',
    professorId: 'prof-2',
    totalPayments: 3,
    totalAttendance: 25,
  },
  {
    id: 'stu-11',
    name: 'Camila Rios Huerta',
    dni: '76543210',
    photoUrl: 'https://picsum.photos/seed/stu11/100/100',
    age: 9,
    gender: 'Femenino',
    guardian: { name: 'Gloria Huerta', dni: '43210765', phone: '990123456' },
    sport: 'Fútbol',
    category: 'Sub 10',
    season: 'Anual 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-3',
    totalPayments: 5,
    totalAttendance: 40,
  },
  {
    id: 'stu-12',
    name: 'Alejandro Muñoz Silva',
    dni: '65432107',
    photoUrl: 'https://picsum.photos/seed/stu12/100/100',
    age: 19,
    gender: 'Masculino',
    phone: '991234567',
    sport: 'Fútbol',
    category: 'Sub 17',
    season: 'Anual 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-1',
    totalPayments: 7,
    totalAttendance: 55,
  },
  {
    id: 'stu-13',
    name: 'Isabella Mendoza Parra',
    dni: '54321076',
    photoUrl: 'https://picsum.photos/seed/stu13/100/100',
    age: 13,
    gender: 'Femenino',
    guardian: { name: 'Rosa Parra', dni: '32107654', phone: '992345678' },
    sport: 'Fútbol',
    category: 'Sub 13',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-2',
    totalPayments: 3,
    totalAttendance: 28,
  },
  {
    id: 'stu-14',
    name: 'Emilio Castro Ibarra',
    dni: '43210765',
    photoUrl: 'https://picsum.photos/seed/stu14/100/100',
    age: 7,
    gender: 'Masculino',
    guardian: { name: 'Miguel Castro', dni: '21076543', phone: '993456789' },
    sport: 'Fútbol',
    category: 'Sub 8',
    season: 'Verano 2026',
    paymentStatus: 'Deuda pendiente',
    professorId: 'prof-3',
    totalPayments: 1,
    totalAttendance: 10,
  },
  {
    id: 'stu-15',
    name: 'Renata Herrera Campos',
    dni: '32107654',
    photoUrl: 'https://picsum.photos/seed/stu15/100/100',
    age: 17,
    gender: 'Femenino',
    guardian: { name: 'Elena Campos', dni: '10765432', phone: '994567890' },
    sport: 'Fútbol',
    category: 'Sub 17',
    season: 'Anual 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-1',
    totalPayments: 6,
    totalAttendance: 48,
  },
];

const now = new Date();

export const requests: ConfirmationRequest[] = [
  {
    id: 'req-1',
    timestamp: subHours(now, 2).toISOString(),
    motive: 'Inscripción/Mensualidad',
    promoterName: 'Sofia Rodriguez',
    status: 'Pendiente',
    student: {
      name: 'Nuevo Alumno Jr.',
      isMinor: true,
      guardianName: 'Padre Ejemplo',
      guardianDni: '78945612',
      guardianPhone: '987654321',
      sport: 'Fútbol',
      category: 'Sub 10',
      schedule: 'L-M-V 9-11am',
      professor: 'Ricardo Mendez',
    },
    payment: {
      evidencePhotoUrl: 'https://picsum.photos/seed/yape/300/500',
      evidenceTimestamp: subHours(now, 3).toISOString(),
      method: 'Yape',
      payerName: 'Padre Ejemplo',
      amount: 85.00,
    },
    promoterNotes: 'El padre indica que es la primera vez que inscribe a su hijo en una academia.',
  },
  {
    id: 'req-2',
    timestamp: subDays(now, 1).toISOString(),
    motive: 'Mensualidad',
    promoterName: 'Luisa Martinez',
    status: 'Confirmado',
    student: {
      name: 'Maria Lopez Torres',
      isMinor: true,
      guardianName: 'Ana Torres',
      guardianDni: '12345678',
      guardianPhone: '912345678',
      sport: 'Fútbol',
      category: 'Sub 13',
      schedule: 'L-V 14-15:30pm',
      professor: 'Carlos Orellano',
    },
    payment: {
      method: 'Efectivo',
      payerName: 'Ana Torres',
      amount: 30.00,
    },
    confirmationTimestamp: addHours(subDays(now, 1), 4).toISOString(),
    observation: {
      notes: 'El pago inicial fue de 20 soles, se solicitó completar y la promotora confirmó la recepción del restante.',
      timestamp: addHours(subDays(now, 1), 2).toISOString(),
      adminEvidencePhotoUrl: 'https://picsum.photos/seed/transfer/300/500',
      adminEvidenceTimestamp: addHours(subDays(now, 1), 1).toISOString(),
    }
  },
  {
    id: 'req-3',
    timestamp: subDays(now, 2).toISOString(),
    motive: 'Deuda',
    promoterName: 'Sofia Rodriguez',
    status: 'Observado',
    student: {
      name: 'Carlos Sanchez Ruiz',
      isMinor: false,
      studentPhone: '998877665',
      sport: 'Fútbol',
      category: 'Sub 17',
      schedule: 'L-M-V 10-12am',
      professor: 'Alberto Domínguez',
    },
    payment: {
      evidencePhotoUrl: 'https://picsum.photos/seed/yape2/300/500',
      evidenceTimestamp: subHours(subDays(now, 2), 1).toISOString(),
      method: 'Yape',
      payerName: 'Carlos Sanchez Ruiz',
      amount: 25.00,
    },
    observation: {
      notes: 'El número de operación en el comprobante no es legible. Por favor, sube una imagen más clara o re-envía la solicitud con el número correcto en las notas.',
      timestamp: addHours(subDays(now, 2), 5).toISOString(),
    },
  },
  {
    id: 'req-4',
    timestamp: subDays(now, 3).toISOString(),
    motive: 'Uniforme',
    promoterName: 'Luisa Martinez',
    status: 'Rechazado',
    student: {
      name: 'Ana Gomez Flores',
      isMinor: true,
      guardianName: 'Luis Gomez',
      guardianDni: '23456789',
      guardianPhone: '987123456',
      sport: 'Fútbol',
      category: 'Sub 10',
      schedule: 'L-M-V-S 9-11am',
      professor: 'Ricardo Mendez',
    },
    payment: {
      evidencePhotoUrl: 'https://picsum.photos/seed/transfer2/300/500',
      evidenceTimestamp: subHours(subDays(now, 3), 1).toISOString(),
      method: 'Transferencia',
      payerName: 'Luis Gomez',
      amount: 55.00,
    },
    rejectionTimestamp: addHours(subDays(now, 3), 8).toISOString(),
    observation: {
        notes: 'La transferencia fue realizada a una cuenta incorrecta y el plazo para la corrección ha expirado. La solicitud ha sido rechazada.',
        timestamp: addHours(subDays(now, 3), 8).toISOString(),
    }
  },
   {
    id: 'req-5',
    timestamp: subHours(now, 1).toISOString(),
    motive: 'Pack 1',
    promoterName: 'Sofia Rodriguez',
    status: 'Pendiente',
    student: {
      name: 'Luis Angel Ramirez',
      isMinor: false,
      studentPhone: '999123456',
      sport: 'Fútbol',
      category: 'Sub 15',
      schedule: 'L-M-V 10-12am',
      professor: 'Alberto Domínguez',
    },
    payment: {
      method: 'Efectivo',
      payerName: 'Luis Angel Ramirez',
      amount: 150.00,
    },
    promoterNotes: 'Alumno nuevo, pagó por el paquete completo de inicio.',
  },
];

export const seasons: Season[] = [
  {
    id: 'season-1',
    name: 'Verano 2026',
    duration: 60,
    studentCount: 80,
    price: 30,
    startDate: '2026-02-05',
    endDate: '2026-04-05',
    paymentDate: '2026-02-01',
    schedule: 'Lunes-Martes-Miércoles-Jueves',
    benefits: 'Entrenamiento intensivo de verano y participación en torneo amistoso.',
  },
  {
    id: 'season-2',
    name: 'Anual 2026',
    duration: 365,
    studentCount: 120,
    price: 30,
    startDate: '2026-01-15',
    endDate: '2026-12-20',
    paymentDate: 'Cada día 5 del mes',
    schedule: 'Varía según categoría',
    benefits: 'Acceso a todas las instalaciones, seguimiento nutricional y descuentos en tienda.',
  },
];

export const packages: Package[] = [
  {
    id: 'pack-1',
    name: 'Pack 1 (Bienvenida)',
    description: 'Inscripción, 1ra mensualidad y uniforme completo.',
    price: 150.00,
  },
  {
    id: 'pack-2',
    name: 'Pack Verano',
    description: 'Acceso completo a la temporada de verano y 2 uniformes de entrenamiento.',
    price: 120.00,
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    imageUrl: getImage('uniform')?.imageUrl ?? 'https://picsum.photos/seed/uniform/200/200',
    imageHint: getImage('uniform')?.imageHint,
    name: 'Camiseta y short',
    category: 'Uniforme',
    stock: 70,
    price: 55.00,
  },
  {
    id: 'prod-2',
    imageUrl: getImage('vest')?.imageUrl ?? 'https://picsum.photos/seed/vest/200/200',
    imageHint: getImage('vest')?.imageHint,
    name: 'Chaleco entrenamiento azul',
    category: 'Uniforme',
    stock: 84,
    price: 35.00,
  },
  {
    id: 'prod-3',
    imageUrl: 'https://picsum.photos/seed/ball/200/200',
    imageHint: 'soccer ball',
    name: 'Balón de fútbol N°5',
    category: 'Accesorio',
    stock: 40,
    price: 80.00,
  },
  {
    id: 'prod-4',
    imageUrl: 'https://picsum.photos/seed/water/200/200',
    imageHint: 'water bottle',
    name: 'Botella de agua 1L',
    category: 'Bebida',
    stock: 150,
    price: 5.00,
  },
];

const today = format(new Date(), 'yyyy-MM-dd');
const yesterday = format(subDays(new Date(), 1), 'yyyy-MM-dd');

export const attendances: Attendance[] = [
  // Today
  { id: 'att-1', studentId: 'stu-1', date: today, status: 'Presente', promoterId: 'user-2' },
  { id: 'att-2', studentId: 'stu-2', date: today, status: 'Falta', promoterId: 'user-2' },
  { id: 'att-3', studentId: 'stu-3', date: today, status: 'Presente', promoterId: 'user-3' },
  { id: 'att-4', studentId: 'stu-4', date: today, status: 'Presente', promoterId: 'user-3' },
  { id: 'att-5', studentId: 'stu-5', date: today, status: 'Falta', promoterId: 'user-2' },
  { id: 'att-6', studentId: 'stu-6', date: today, status: 'Presente', promoterId: 'user-2' },
  { id: 'att-7', studentId: 'stu-7', date: today, status: 'Presente', promoterId: 'user-3' },
  { id: 'att-8', studentId: 'stu-8', date: today, status: 'Presente', promoterId: 'user-2' },
  { id: 'att-9', studentId: 'stu-9', date: today, status: 'Falta', promoterId: 'user-3' },
  { id: 'att-10', studentId: 'stu-10', date: today, status: 'Presente', promoterId: 'user-2' },
  // Yesterday
  { id: 'att-11', studentId: 'stu-1', date: yesterday, status: 'Presente', promoterId: 'user-2' },
  { id: 'att-12', studentId: 'stu-2', date: yesterday, status: 'Presente', promoterId: 'user-2' },
  { id: 'att-13', studentId: 'stu-3', date: yesterday, status: 'Presente', promoterId: 'user-3' },
  { id: 'att-14', studentId: 'stu-4', date: yesterday, status: 'Falta', promoterId: 'user-3' },
  { id: 'att-15', studentId: 'stu-5', date: yesterday, status: 'Presente', promoterId: 'user-2' },
];
