import {
  Student,
  Professor,
  Category,
  ConfirmationRequest,
  Season,
  Package,
  Product,
  Attendance,
  User,
} from './types';
import { subDays, subHours, addHours, format } from 'date-fns';
import { getImage } from './placeholder-images';

export const users: User[] = [
  { id: 'user-1', name: 'Admin', email: 'admin@sportingclub.com', avatarUrl: 'https://picsum.photos/seed/admin/100/100', role: 'Administrador' },
  { id: 'user-2', name: 'Sofia Rodriguez', email: 'sofia@sportingclub.com', avatarUrl: 'https://picsum.photos/seed/promo1/100/100', role: 'Promotora' },
  { id: 'user-3', name: 'Luisa Martinez', email: 'luisa@sportingclub.com', avatarUrl: 'https://picsum.photos/seed/promo2/100/100', role: 'Promotora' },
]

export const professors: Professor[] = [
  {
    id: 'prof-1',
    name: 'Alberto Domínguez',
    sport: 'Fútbol',
    phone: '987654321',
    email: 'alberto.d@example.com',
    categoryIds: ['cat-15'],
  },
  {
    id: 'prof-2',
    name: 'Carlos Orellano',
    sport: 'Fútbol',
    phone: '912345678',
    email: 'carlos.o@example.com',
    categoryIds: ['cat-13', 'cat-12'],
  },
  {
    id: 'prof-3',
    name: 'Ricardo Mendez',
    sport: 'Fútbol',
    phone: '998877665',
    email: 'ricardo.m@example.com',
    categoryIds: ['cat-10'],
  },
];

export const categories: Category[] = [
  {
    id: 'cat-15',
    name: 'Categoría 15',
    sport: 'Fútbol',
    ageRange: [15, 16],
    maxCapacity: 30,
    enrolledStudents: 28,
    professors: ['Alberto Domínguez'],
    schedule: {
      days: ['Lunes', 'Miércoles', 'Viernes'],
      time: '10:00 a 12:00',
      durationPerClass: '2 horas',
      frequency: '3 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-05',
  },
  {
    id: 'cat-13',
    name: 'Categoría 13',
    sport: 'Fútbol',
    ageRange: [13, 14],
    maxCapacity: 30,
    enrolledStudents: 30,
    professors: ['Carlos Orellano'],
    schedule: {
      days: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
      time: '14:00 a 15:30',
      durationPerClass: '1 hora y 30 minutos',
      frequency: '5 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-06',
  },
  {
    id: 'cat-10',
    name: 'Categoría 10',
    sport: 'Fútbol',
    ageRange: [10, 12],
    maxCapacity: 20,
    enrolledStudents: 18,
    professors: ['Ricardo Mendez'],
    schedule: {
      days: ['Lunes', 'Miércoles', 'Viernes', 'Sábado'],
      time: '09:00 a 11:00',
      durationPerClass: '2 horas',
      frequency: '4 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-06',
  },
  {
    id: 'cat-12',
    name: 'Categoría 12',
    sport: 'Fútbol',
    ageRange: [12, 13],
    maxCapacity: 25,
    enrolledStudents: 22,
    professors: ['Carlos Orellano'],
    schedule: {
      days: ['Martes', 'Jueves', 'Sábado'],
      time: '16:00 a 18:00',
      durationPerClass: '2 horas',
      frequency: '3 veces por semana',
    },
    price: 30.00,
    startDate: '2026-02-07',
  },
];

export const students: Student[] = [
  {
    id: 'stu-1',
    name: 'Juan Perez Garcia',
    dni: '78945612',
    photoUrl: 'https://picsum.photos/seed/stu1/100/100',
    age: 15,
    gender: 'Masculino',
    guardian: { name: 'Mario Perez', dni: '45612378', phone: '987654321' },
    sport: 'Fútbol',
    category: 'Categoría 15',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-1',
    totalPayments: 3,
    totalAttendance: 22,
  },
  {
    id: 'stu-2',
    name: 'Maria Lopez Torres',
    dni: '87654321',
    photoUrl: 'https://picsum.photos/seed/stu2/100/100',
    age: 13,
    gender: 'Femenino',
    guardian: { name: 'Ana Torres', dni: '12345678', phone: '912345678' },
    sport: 'Fútbol',
    category: 'Categoría 13',
    season: 'Verano 2026',
    paymentStatus: 'Deuda pendiente',
    professorId: 'prof-2',
    totalPayments: 1,
    totalAttendance: 15,
  },
  {
    id: 'stu-3',
    name: 'Carlos Sanchez Ruiz',
    dni: '12345679',
    photoUrl: 'https://picsum.photos/seed/stu3/100/100',
    age: 18,
    gender: 'Masculino',
    phone: '998877665',
    sport: 'Fútbol',
    category: 'Categoría 15',
    season: 'Anual 2026',
    paymentStatus: 'Próximo a vencer',
    professorId: 'prof-1',
    totalPayments: 5,
    totalAttendance: 45,
  },
  {
    id: 'stu-4',
    name: 'Ana Gomez Flores',
    dni: '98765432',
    photoUrl: 'https://picsum.photos/seed/stu4/100/100',
    age: 10,
    gender: 'Femenino',
    guardian: { name: 'Luis Gomez', dni: '23456789', phone: '987123456' },
    sport: 'Fútbol',
    category: 'Categoría 10',
    season: 'Verano 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-3',
    totalPayments: 2,
    totalAttendance: 18,
  },
  {
    id: 'stu-5',
    name: 'Pedro Ramirez Soto',
    dni: '54321678',
    photoUrl: 'https://picsum.photos/seed/stu5/100/100',
    age: 12,
    gender: 'Masculino',
    guardian: { name: 'Laura Soto', dni: '67891234', phone: '976543210' },
    sport: 'Fútbol',
    category: 'Categoría 12',
    season: 'Anual 2026',
    paymentStatus: 'Al día',
    professorId: 'prof-2',
    totalPayments: 6,
    totalAttendance: 50,
  },
];

const now = new Date();

export const requests: ConfirmationRequest[] = [
  {
    id: 'req-1',
    timestamp: subHours(now, 2).toISOString(),
    motive: 'Inscripción/Mensualidad',
    promoterName: 'Sofia Rodriguez',
    status: 'Pendiente',
    student: {
      name: 'Nuevo Alumno Jr.',
      isMinor: true,
      guardianName: 'Padre Ejemplo',
      guardianDni: '78945612',
      guardianPhone: '987654321',
      sport: 'Fútbol',
      category: 'Categoría 10',
      schedule: 'L-M-V 9-11am',
      professor: 'Ricardo Mendez',
    },
    payment: {
      evidencePhotoUrl: 'https://picsum.photos/seed/yape/300/500',
      evidenceTimestamp: subHours(now, 3).toISOString(),
      method: 'Yape',
      payerName: 'Padre Ejemplo',
      amount: 85.00,
    },
    promoterNotes: 'El padre indica que es la primera vez que inscribe a su hijo en una academia.',
  },
  {
    id: 'req-2',
    timestamp: subDays(now, 1).toISOString(),
    motive: 'Mensualidad',
    promoterName: 'Luisa Martinez',
    status: 'Confirmado',
    student: {
      name: 'Maria Lopez Torres',
      isMinor: true,
      guardianName: 'Ana Torres',
      guardianDni: '12345678',
      guardianPhone: '912345678',
      sport: 'Fútbol',
      category: 'Categoría 13',
      schedule: 'L-V 14-15:30pm',
      professor: 'Carlos Orellano',
    },
    payment: {
      method: 'Efectivo',
      payerName: 'Ana Torres',
      amount: 30.00,
    },
    confirmationTimestamp: addHours(subDays(now, 1), 4).toISOString(),
    observation: {
      notes: 'El pago inicial fue de 20 soles, se solicitó completar y la promotora confirmó la recepción del restante.',
      timestamp: addHours(subDays(now, 1), 2).toISOString(),
      adminEvidencePhotoUrl: 'https://picsum.photos/seed/transfer/300/500',
      adminEvidenceTimestamp: addHours(subDays(now, 1), 1).toISOString(),
    }
  },
  {
    id: 'req-3',
    timestamp: subDays(now, 2).toISOString(),
    motive: 'Deuda',
    promoterName: 'Sofia Rodriguez',
    status: 'Observado',
    student: {
      name: 'Carlos Sanchez Ruiz',
      isMinor: false,
      studentPhone: '998877665',
      sport: 'Fútbol',
      category: 'Categoría 15',
      schedule: 'L-M-V 10-12am',
      professor: 'Alberto Domínguez',
    },
    payment: {
      evidencePhotoUrl: 'https://picsum.photos/seed/yape2/300/500',
      evidenceTimestamp: subHours(subDays(now, 2), 1).toISOString(),
      method: 'Yape',
      payerName: 'Carlos Sanchez Ruiz',
      amount: 25.00,
    },
    observation: {
      notes: 'El monto de la deuda es de S/ 30.00, el pago de S/ 25.00 es incompleto. Favor de regularizar.',
      timestamp: addHours(subDays(now, 2), 5).toISOString(),
    },
  },
  {
    id: 'req-4',
    timestamp: subDays(now, 3).toISOString(),
    motive: 'Uniforme',
    promoterName: 'Luisa Martinez',
    status: 'Rechazado',
    student: {
      name: 'Ana Gomez Flores',
      isMinor: true,
      guardianName: 'Luis Gomez',
      guardianDni: '23456789',
      guardianPhone: '987123456',
      sport: 'Fútbol',
      category: 'Categoría 10',
      schedule: 'L-M-V-S 9-11am',
      professor: 'Ricardo Mendez',
    },
    payment: {
      evidencePhotoUrl: 'https://picsum.photos/seed/transfer2/300/500',
      evidenceTimestamp: subHours(subDays(now, 3), 1).toISOString(),
      method: 'Transferencia',
      payerName: 'Luis Gomez',
      amount: 55.00,
    },
    rejectionTimestamp: addHours(subDays(now, 3), 8).toISOString(),
    observation: {
        notes: 'La imagen de la transferencia no es legible. Por favor, enviar una captura de pantalla más clara.',
        timestamp: addHours(subDays(now, 3), 8).toISOString(),
    }
  },
   {
    id: 'req-5',
    timestamp: subHours(now, 1).toISOString(),
    motive: 'Pack 1',
    promoterName: 'Sofia Rodriguez',
    status: 'Pendiente',
    student: {
      name: 'Luis Angel Ramirez',
      isMinor: false,
      studentPhone: '999123456',
      sport: 'Fútbol',
      category: 'Categoría 15',
      schedule: 'L-M-V 10-12am',
      professor: 'Alberto Domínguez',
    },
    payment: {
      method: 'Efectivo',
      payerName: 'Luis Angel Ramirez',
      amount: 150.00,
    },
    promoterNotes: 'Alumno nuevo, pagó por el paquete completo de inicio.',
  },
];

export const seasons: Season[] = [
  {
    id: 'season-1',
    name: 'Verano 2026',
    duration: 60,
    studentCount: 80,
    price: 30,
    startDate: '2026-02-05',
    endDate: '2026-04-05',
    paymentDate: '2026-02-01',
    schedule: 'Lunes-Martes-Miércoles-Jueves',
    benefits: 'Entrenamiento intensivo de verano y participación en torneo amistoso.',
  },
  {
    id: 'season-2',
    name: 'Anual 2026',
    duration: 365,
    studentCount: 120,
    price: 30,
    startDate: '2026-01-15',
    endDate: '2026-12-20',
    paymentDate: 'Cada día 5 del mes',
    schedule: 'Varía según categoría',
    benefits: 'Acceso a todas las instalaciones, seguimiento nutricional y descuentos en tienda.',
  },
];

export const packages: Package[] = [
  {
    id: 'pack-1',
    name: 'Pack 1 (Bienvenida)',
    description: 'Inscripción, 1ra mensualidad y uniforme completo.',
    price: 150.00,
  },
  {
    id: 'pack-2',
    name: 'Pack Verano',
    description: 'Acceso completo a la temporada de verano y 2 uniformes de entrenamiento.',
    price: 120.00,
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    imageUrl: getImage('uniform')?.imageUrl ?? 'https://picsum.photos/seed/uniform/200/200',
    imageHint: getImage('uniform')?.imageHint,
    name: 'Camiseta y short',
    category: 'Uniforme',
    stock: 70,
    price: 55.00,
  },
  {
    id: 'prod-2',
    imageUrl: getImage('vest')?.imageUrl ?? 'https://picsum.photos/seed/vest/200/200',
    imageHint: getImage('vest')?.imageHint,
    name: 'Chaleco entrenamiento azul',
    category: 'Uniforme',
    stock: 84,
    price: 35.00,
  },
  {
    id: 'prod-3',
    imageUrl: 'https://picsum.photos/seed/ball/200/200',
    imageHint: 'soccer ball',
    name: 'Balón de fútbol N°5',
    category: 'Accesorio',
    stock: 40,
    price: 80.00,
  },
  {
    id: 'prod-4',
    imageUrl: 'https://picsum.photos/seed/water/200/200',
    imageHint: 'water bottle',
    name: 'Botella de agua 1L',
    category: 'Bebida',
    stock: 150,
    price: 5.00,
  },
];

export const attendances: Attendance[] = [
  { id: 'att-1', studentId: 'stu-1', date: format(new Date(), 'yyyy-MM-dd'), status: 'Presente', promoterId: 'user-2' },
  { id: 'att-2', studentId: 'stu-2', date: format(new Date(), 'yyyy-MM-dd'), status: 'Falta', promoterId: 'user-2' },
  { id: 'att-3', studentId: 'stu-3', date: format(new Date(), 'yyyy-MM-dd'), status: 'Presente', promoterId: 'user-3' },
  { id: 'att-4', studentId: 'stu-4', date: format(new Date(), 'yyyy-MM-dd'), status: 'Presente', promoterId: 'user-3' },
  { id: 'att-5', studentId: 'stu-5', date: format(new Date(), 'yyyy-MM-dd'), status: 'Falta', promoterId: 'user-2' },
  { id: 'att-6', studentId: 'stu-1', date: format(subDays(new Date(), 1), 'yyyy-MM-dd'), status: 'Presente', promoterId: 'user-2' },
  { id: 'att-7', studentId: 'stu-2', date: format(subDays(new Date(), 1), 'yyyy-MM-dd'), status: 'Presente', promoterId: 'user-2' },
];
